<?php

use Drupal\Component\Utility\Html;

/**
 * @file
 * This module allows you to protect any page of your website by secure
 * password. You can enter urls of pages to protect and set password per page.
 * Admin (uid = 1) or user with bypass protection permission can view page.
 */

/**
 * Implements hook_mail().
 *
 */
function protected_pages_mail($key, &$message, $params) {

    switch ($key) {
        // Send a simple message from the contact form.
        case 'protected_pages_details_mail':

            $tokens = array('[protected-page-url]', '[site-name]');
            $replcements = array(
                $params['protected_page_url'], \Drupal::config('system.site')->get('name'),
            );

            $body = str_replace($tokens, $replcements, $params['body']);

            $subject = $params['subject'];
            $message['subject'] = Html::escape($subject);
            $message['body'][] = Html::escape($body);

            break;
    }
}

